version: '3.8'

services:
  postgresIntranet:
    image: postgres:15
    container_name: postgres_intranet_db
    environment:
      POSTGRES_USER: kch
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: kch
      TZ: Asia/Seoul
    ports:
      - "5433:5432"
    volumes:
      - C:/intranetData:/var/lib/postgresql/data
    networks:
      - nat

volumes:
  postgres_data:

networks:
  nat:
    driver: bridge