spring:
  application:
    name: intranet
  jpa:
    show-sql: true
    generate-ddl: true
    database: postgresql
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/kch}
    username: kch
    password: 12345
server:
  port: 8081
